language: c++

dist: trusty
sudo: required
matrix:
  include:
    - os: linux
      compiler: gcc-6
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - cmake
            - cmake-data
            - libbullet-dev
            - libglu1-mesa-dev
            - libx11-dev
            - libxxf86vm-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
      env:
        - C_COMPILER=gcc-6
        - CXX_COMPILER=g++-6
    - os: linux
      compiler: clang-3.9
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
          packages:
            - g++-6
            - clang-3.9
            - cmake
            - cmake-data
            - libbullet-dev
            - libglu1-mesa-dev
            - libx11-dev
            - libxxf86vm-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
      env:
        - C_COMPILER=clang-3.9
        - CXX_COMPILER=clang++-3.9
    - os: osx
      compiler: clang
      env:
        - C_COMPILER=clang
        - CXX_COMPILER=clang++

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/glfw

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew install glfw bullet
    fi

  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export GLFW_ROOT="${TRAVIS_BUILD_DIR}/deps/glfw"
      if [[ -z "$(ls -A ${GLFW_ROOT})" ]]; then
        (
          travis_retry git clone --depth 1 -b 3.3.2 https://github.com/glfw/glfw.git
          cd glfw && mkdir build && cd build
          cmake -D GLFW_INSTALL=ON -D GLFW_BUILD_EXAMPLES=OFF \
            -D GLFW_BUILD_DOCS=OFF -D GLFW_BUILD_TESTS=OFF \
            -D CMAKE_INSTALL_PREFIX=${GLFW_ROOT} ..
          make install
        )
      fi
    fi
  
script:
  - mkdir build && cd build ;
    cmake -D CMAKE_C_COMPILER=${C_COMPILER} -D CMAKE_CXX_COMPILER=${CXX_COMPILER} -D SABA_GLFW_ROOT=${GLFW_ROOT} .. ;
    make -j2
